name: Dump cluster state
description: "Creates an artifacts with cluster dump"

runs:
  using: "composite"
  steps:

    - name: Dump cluster state
      shell: bash
      run: |
        echo "Dumping cluster info into ${{ env.EXTENSION_DIR }}"
