on: [pull_request]
name: Check links for modified files

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: First script from job1
        run: echo We use the global workflow variable $PR_NUMBER
  job2:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - name: First script from job2
        run: echo We use the global workflow variable $PR_NUMBER
