name: CI

on:
  workflow_dispatch:

  # Triggers the workflow on push for the master branch
  push:
    branches: [ master ]

env:
  EXTENSION_DIR: "test-dir"

jobs:
  generate-a-secret-output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Call composite
        uses: ./.github/actions/shared
