name: CI

on:
  workflow_dispatch:

env:
  EXTENSION_DIR: "test-dir"

jobs:
  generate-a-secret-output:
    runs-on: ubuntu-latest
    steps:
      - name: Call composite
        uses: ./.github/actions/shared
