name: learn-github-actions

on: workflow_dispatch

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Post blocks to a Slack channel
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            username: "Workload Autoscaler E2E"
            icon_emoji: ":x:"
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  text: "❌ E2E Test Failed"
                  emoji: true
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "*Workflow:* learn-github-actions\n*Job:* check-bats-version\n*Status:* `${{ job.status }}`"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "🔗 *Run details:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View on GitHub>"
              - type: "context"
                elements:
                  - type: "mrkdwn"
                    text: "Triggered by: ${{ github.actor }}"
